---
- name: Install and configure Jenkins Master
  hosts: jenkins-master
  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins APT key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins APT repository
      apt_repository:
        repo: "deb http://pkg.jenkins.io/debian binary/"
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started