---
- name: Install and configure Jenkins Agents
  hosts: jenkins-agents
  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Download Jenkins Agent JAR
      get_url:
        url: http://<jenkins-master>:<jenkins-port>/jnlpJars/agent.jar
        dest: /home/{{ ansible_user }}/agent.jar
        mode: 0755

    - name: Configure Jenkins Agent as a service
      systemd:
        name: jenkins-agent
        enabled: yes
        state: started
        daemon_reload: yes
        unit_content: |
          [Unit]
          Description=Jenkins Agent
          After=network.target

          [Service]
          User={{ ansible_user }}
          ExecStart=/usr/bin/java -jar /home/{{ ansible_user }}/agent.jar -jnlpUrl http://<jenkins-master>:<jenkins-port>/computer/{{ inventory_hostname }}/slave-agent.jnlp
          Restart=always

          [Install]
          WantedBy=multi-user.target
